<?php

namespace AppBundle\Repository;

/**
 * shops1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shops1Repository extends \Doctrine\ORM\EntityRepository
{
}